from __future__ import annotations

# Default LLM settings
DEFAULT_MODEL = "claude-3-5-sonnet-20241022"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_MAX_TOKENS = 4096

# Retrieval
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 200
DEFAULT_RETRIEVAL_K = 4
DEFAULT_SEARCH_RESULTS = 5
SIMILARITY_THRESHOLD = 0.5

# Hybrid search
BM25_WEIGHT = 0.4
SEMANTIC_WEIGHT = 0.6
RRF_K = 60

# Supervisor
MAX_SUPERVISOR_ITERATIONS = 10

# Cache
DEFAULT_CACHE_TTL = 3600  # seconds
MAX_CACHE_SIZE = 512  # entries

# Rate limiting
DEFAULT_RATE_LIMIT_REQUESTS = 60
DEFAULT_RATE_LIMIT_WINDOW = 60  # seconds

# Batch processing
DEFAULT_BATCH_CONCURRENCY = 5
MAX_BATCH_SIZE = 50

# Streaming
STREAM_CHUNK_SIZE = 32  # tokens per yield

# Eval
DEFAULT_EVAL_CONCURRENCY = 3
MIN_FAITHFULNESS_SCORE = 0.7


# Eval thresholds
MIN_ANSWER_RELEVANCE = 0.6
MIN_CONTEXT_RECALL = 0.5
MIN_FAITHFULNESS = 0.7

# Logging
LOG_MAX_QUERY_CHARS = 120
LOG_MAX_CONTENT_CHARS = 500


# API
DEFAULT_REQUEST_TIMEOUT = 30  # seconds
MAX_CONTENT_LENGTH = 10 * 1024 * 1024  # 10 MB

# Context window
CONTEXT_WINDOW_TOKENS = 8000
SYSTEM_PROMPT_BUDGET = 1500
